FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt && uvicorn --version
COPY api.py .
COPY maintenance.db .
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
