services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./database:/app/database
      - ./logs:/app/logs
      - ./models:/app/models
    networks:
      - ship-net
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app
      - ./database:/app/database
      - ./models:/app/models
    networks:
      - ship-net
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    networks:
      - ship-net
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - ship-net
networks:
  ship-net:
    driver: bridge
