services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database
    networks:
      - ship-net
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    networks:
      - ship-net
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ship-net
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - ship-net
networks:
  ship-net:
    driver: bridge
