global:
  scrape_interval: 5s
  scrape_timeout: 5s
scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['third-officer-maintenance-system-api-1:8000']
